name: Build and Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test:report
      - name: Upload Testing Report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: out/report/
      - name: Archive
        run: npm run archive
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: archive
          path: out/artifact/archive.zip
      - name: Create Comments
        run: |
          # Using GitHub API to create a comment on the PR
          PR_NUMBER=${{ github.event.pull_request.number }}
          COMMENT="**BUILD SUCCEED** :rocket:\nworkflow run-id: [${{ github.run_id }}](https://github.com/nick10811/webhook-recevier/actions/runs/${{ github.run_id }})"
          GITHUB_TOKEN=${{ secrets.BOT_TOKEN }}
          COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
          curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST -d "{\"body\": \"${COMMENT}\"}" "${COMMENT_URL}"